apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/44smkn/myapp:v1.0.0
        name: myapp
      - env:
        - name: NGINX_PORT
          value: "80"
        image: nginx:stable
        imagePullPolicy: IfNotPresent
        name: nginx
