apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          env:
            - name: NGINX_PORT
              value: "80"
        - image: ghcr.io/44smkn/myapp:v1.0.0
          name: myapp
