apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          env:
            - name: NGINX_HOST
              value: foobar.com
